# Site settings
title: Hoang Hai NGUYEN
twitter_username: NGUYENHOANGHAI
name: NGUYEN HOANG HAI

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/https://github.com/hoanghainguyen
  - title: LinkedIn
   url: https://www.linkedin.com/in/hoanghainguyen
  - title: website
   url: https://itoutsourcer.com

#Any buzzword skills you want to include
skills:
- JQUERY
- XML
- XSLT
- XSL
- Maven
- Ant 
- Java
- C# 
- C++
- C
- JPA
- HIBERNATE
- SQL
- LIFERAY
- EXO PLATEFORM
- JSR 286
- JSR 168
- AS2 Messaging
- AS4 Messaging
- OASIS ebMS 3.0,
- Tech Architecture
- POWERDESIGNER
- INTELLIJ IDEA
- JREBEL
- AXURE
- FIREBUG
 

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: http://automateddeveloper.blogspot.com/feeds/posts/default

#Work experience is required
roles:
 - title: Java Middleware Engineer
   start: 2015
   end: Ongoing
   employer:E
   description: Emerald Street Ventures was established as an incubator vehicle for the development of a number of software and legal-tech projects, and a rapidly growing, London-based start-up using innovative technologies to revolutionise and change the software and legal-tech landscape. Working with a range of cutting edge technologies and techniques including Scala, Cassandra, CoreOS, a variety of Machine Learning techniques.
 - title: Senior Engineer
   start: 2012
   end: 2016
   employer: Covestor
   description: Covestor is an investment marketplace startup that was successfully acquired by Interactive Brokers in 2015. <br/> I am a senior engineer working closely with the CTO, working across the full-stack, I am involved in all aspects of the technology including the website and back-end services.
 - title: Associate Manager
   start: 2005
   end: 2012
   employer: Accenture
   description: A range of functional and technical roles, primarily working on client sites in Financial Services.

#Education is required
education:
 - level: Master of Applied Computer Sciences
   subject: Artificial Intelligence and Computer Science
   school: VUB(Free University of Brussels)


#List of interesting Github repo/projects to include - optional
github:
 - https://github.com/hoanghainguyen/FilteringTable
 
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   AS2 Messaging, AS4 Messaging, OASIS ebMS 3.0, e-SENS

ECM, PORTALS

LIFERAY, WEB SPACE SUN GLASSFISH, EXO PLATEFORM, KNOWLEDGE TREE, JSR 168, JSR 286, JSR 170 SPECIFICATION

PROGRAMMING LANGUAGES

JAVA 1.4, 1.6, 1.7 JEE (JSP, SERVLET, PORTLET), JAVASCRIPT, JQUERY, XML, XSLT, XSL, C# (ASP .NET, ADO.NET 2.0), SQL, C, C++, VB, PHP, FLEX, JAVASCRIPT, JQUERY, HTML, CSS.

TOOLS

SERVICEBUILDER BUILT IN OF LIFERAY (CODE GENERATOR), NETBEANS , ECLIPSE, ENTELLIGVISUAL SOURCESAFE, MICROSOFT VISIO AND MS IIS, CYGWIN, SYBASE CENTRAL, SYBASE ADVANTAGE, SUBVERSION, TORTOISE SVN, SYNCRHO SVN, LOMBOZ, FIREBUG,SYBASE’S POWERDESIGNER, INTELLIJ IDEA 15, JREBEL, AXURE.

FRAMEWORK
HIBERNATE, SPRING, STRUTS, ICEFACES, JSF, PRIMEFACES, QUAZT, VELOCITY, ANT, MAVEN, VAADIN 6, VAADIN 7.6.8
